# Generated by Django 3.2.12 on 2022-08-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="transaction_context",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
