# Generated by Django 3.2.12 on 2022-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_transaction_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
