# Generated by Django 4.2.1 on 2023-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_payment_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
