# Generated by Django 3.2.12 on 2022-02-20 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participant",
            field=models.ManyToManyField(
                blank=True,
                related_name="participant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="event participants",
            ),
        ),
    ]
