# Generated by Django 3.2.12 on 2022-02-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_members'),
        ('event', '0002_alter_event_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organization.organization', verbose_name='event organization'),
        ),
    ]
