# Generated by Django 3.2.12 on 2022-06-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_auto_20220304_0451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("EXPIRED", "EXPIRED"),
                    ("SCHEDULED", "SCHEDULED"),
                ],
                max_length=50,
            ),
        ),
    ]
