# Generated by Django 3.2.12 on 2022-07-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20220618_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('INVALID', 'INVALID')], max_length=20),
        ),
    ]
