# Generated by Django 3.2.12 on 2022-07-02 22:43

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20220702_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=event.models.get_ticket_id, max_length=256),
        ),
    ]
