# Generated by Django 4.2.1 on 2023-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_eventpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
