# Generated by Django 4.2.1 on 2023-05-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_event_event_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="rsvp",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
