# Generated by Django 4.2.1 on 2023-05-25 23:32

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0015_alter_event_amount_alter_event_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="currency",
            field=models.CharField(default=event.models.get_currency, max_length=5),
        ),
    ]
