# Generated by Django 4.2.1 on 2023-05-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0017_event_participant_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="remaining_slots",
            field=models.IntegerField(default=0),
        ),
    ]
