# Generated by Django 4.2.2 on 2023-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0018_event_remaining_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="check_type",
            field=models.CharField(
                choices=[("CHEC_IN", "CHECK_IN"), ("CHECK_OUT", "CHECK_OUT")],
                default="CHEC_IN",
                max_length=50,
            ),
        ),
    ]
