# Generated by Django 3.2.12 on 2022-07-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER'), ('SUPER_ADMIN', 'SUPER_ADMIN')], default='USER', max_length=300),
        ),
    ]
