# Generated by Django 3.2.12 on 2022-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("ADMIN", "ADMIN"), ("USER", "USER")],
                default="USER",
                max_length=300,
            ),
        ),
    ]
